name: Deploy

on:
  workflow_dispatch:
env:
  APPLICATION_PORT: 8090
  PROJECT_DIRECTORY: videoConverter
  PRODUCTION_BRANCH: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.PROJECT_DIRECTORY }}
            chmod +x mvnw
            git switch ${{ env.PRODUCTION_BRANCH }}
            git pull
            kill $(lsof -ti:${{ env.APPLICATION_PORT }})
            sleep 10;mvn -B clean
            ./mvnw -B package
            (nohup java -Dspring.profiles.active=prod -jar target/*.jar > /dev/null 2>&1 &)