name: Package Project

on:
  workflow_dispatch:

jobs:
  package:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Permissison
          run: chmod +x mvnw
        - name: package jar
          run: ./mvnw -B package
        - uses: actions/upload-artifact@v3
          with:
            name: video_back_runnableJar
            path: target/*.jar